### ISSUE TITLE
Bottom bar with "Draw" is covered after entering initiative

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#1]
We've used Frosthaven assistant in two Crimson Scales scenarios, and it's working great.  I've seen just one significant issue, which occurs on an Nvidia Shield Tablet K1 (Android): after the players' initiatives are entered, the Android navigation bar covers the bottom app bar with the Draw button.  Taking a screen shot drives the Android nav bar away, so I've illustrated the issue by taking a photograph of the device.  One hopes there is an API call to prevent that.  (It's not a show-stopping bug, because the nav bar can be driven away by first tapping on the square to show the list of active apps, then tapping on Frosthaven Assistant to bring the app back to the foreground.)

ETA: The version we're using is [v1.0.0-alpha.2](https://github.com/Tarmslitaren/FrosthavenAssistant/releases/tag/v1.0.0-alpha.2)

A couple of minor comments:

  - On a phone (Moto G5 plus), the interface is a bit crowded with some information lost.  In particular, the monsters' attack-modifier deck covers the coin-value icon. Screen shot is attached for that.
  - The tablet is pretty large, and the blue/white colored background is kind of distracting.  The texture is nice to have, but maybe its color contrast could dialed down significantly?  Just a thought.

![Tablet with Android navigation bar](https://user-images.githubusercontent.com/37659/183486492-3c0694a5-5d0e-45df-98ce-7663f9ab235d.jpg)

![Phone with crowded interface](https://user-images.githubusercontent.com/37659/183487142-55f1c4ed-0652-45ee-8eb5-d1d755986169.jpg)

**Comment by Tarmslitaren** [comment]
Thank you for great feedback! 
These issues should all be fixed in the new beta 1 release:
1. If there is not enough room on the bottom bar , the modifier cards move up.
2. I didn't change the brightness/contrast on the background image, (tried it, but was hard to make it look good) however there is now a 'dark mode' with more muted assets
3. There is a potential fix for the fullscreen restoration bug, but as I don't have an actual device with a software navigation bar to test with, please report back if it doesn't work. As a separate workaround you could untick fullscreeen mode in settings to always show the system ui, however the app will lose some of it's height.

**Comment by nrnrnr** [comment]
FYI the beta (early access 1.0 on Google Play Store) completely resolves the issue with the software navigation bar.  Thank you!!!!
