### ISSUE TITLE
Character initiatives can't be entered in client/server mode

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#10]
Running version 1.2.0 on two different Android devices.  I set up one as a server and the other as a client, without incident.  Scenario state was correctly reflected on both screens.  However, in this mode, character initiatives displayed as `??`, and although the number pad could be tapped in the initiative area, the numbers were immediately overwritten with more question marks.  The same thing happened on both client and server instances.

It's possible the the initiative was there but invisible. However, taking no chances, we took the server machine out of server mode.  The ability to enter character initiatives was immediately restored.

**Comment by Tarmslitaren** [comment]
Expected behavior is: set init value from one device - should show as ?? on all other devices, but shows real value on the local device.

You should be able to change the init value even when they do not originate from same device (i.e. the ?? is shown) 
Since you typically do not want to change someone else's init, and you may mis-click, the initiative is not immediately cleared, when tapping the init field.

If you end up being blocked from setting initiative at all, then please clarify. 
Are you using the 'soft numpad' option from the settings?

**Comment by nrnrnr** [comment]
> Expected behavior is: set init value from one device - should show as ?? on all other devices, but shows real value on the local device

I'm afraid it is showing as `??` on the local device.  I'll check the settings tonight and will clarify.

**Comment by nrnrnr** [comment]
I have not been able to reproduce this issue.   On our two devices everything is working exactly as you would hope.

After a ton of experiments I can guess what happened: somehow during the setup the devices got into a race condition such that `??` was showing for _all_ characters on _all_ devices.  Somehow each device thought the other had both initiatives.

Based on the hint you gave me, if I see `??` on any device I can set that initiative through a 3-step process:

 1. Select all
 2. Cut
 3. Tap to enter initiative

Anyway, everything is working fine now, and my guess is I’ll never see this condition again.  If I can create it reproducibly i will reopen the ticket.
