### ISSUE TITLE
[Feature Request] Add Enhancement indicator to loot cards

### ISSUE THREAD

**Issue by TylerHelmuth** [Tarmslitaren/FrosthavenAssistant#101]
We recently enhanced our first loot card (Lumber 1 -> Lumber 2) and it would be really cool to see when we draw it.

**Comment by SaschB** [comment]
This feature already exists, have you discovered a bug with it?

If you open the loot deck (by tapping on the area where face up loot cards go) there are options at the top for modifying the loot deck. Under "Enhance cards" you should be able to add value to each individual card, and it should be displayed when drawn (e.g. by showing "+2" instead of the normal "+1").

If you've done this, but it still doesn't work, try to describe the context a bit more.

**Comment by TylerHelmuth** [comment]
When we draw the enhanced card is it possible to distinguish it from the other +2 cards?

**Comment by SaschB** [comment]
Oh I see, that I don't know, I misunderstood the question.

**Comment by Tarmslitaren** [comment]
There is no way to distinguish currently. Any suggestions how you would like it to look?

**Comment by TylerHelmuth** [comment]
Could be cool to try an replicate the font/style of the `+1` stickers and slap it anywhere on the card. But that may be confusing with the actual reported value.  Maybe just the word `enhanced` somewhere?

**Comment by Tarmslitaren** [comment]
extra +1, that would be too confusing. got a cheap idea: I can just write 'enhanced' on the card :D

**Comment by SaschB** [comment]
If it's just for some flair, perhaps the "shine" animation from the monster ability cards could be used for the enhanced loot cards' "+X" text?

**Comment by Tarmslitaren** [comment]
dammit. was gonna so that and now the surprise is ruined 🤣

**Comment by TylerHelmuth** [comment]
I believe this has been implemented
