### ISSUE TITLE
Double draw of Monster & Ally attack cards

### ISSUE THREAD

**Issue by grimtoothy** [Tarmslitaren/FrosthavenAssistant#116]
When there is a monster and an ally deck, sometimes clicking on one deck draws from both simulatenously.

**Comment by Tarmslitaren** [comment]
I would be very grateful if anyone can figure out reproducible steps for this :)

I assume it's when playing connected?

**Comment by grimtoothy** [comment]
I'll try to replicate.  I play with two others - networked.  Its annoying, but it only happens during the first draw for a new monster/ally.  Second draws, as along as the initiate tracker doesn't advance, then draw only from one deck.

i suspect its due to me drawing from the wrong deck.  It would be nice to prevent that - or make it obvious which deck is assigned to which enemies.  Maybe add a symbol in corner for groups of monsters?  Or color code the deck and the corresponding monsters?

If it helps, this was happening during Frosthaven Scenario #3.

**Comment by Tarmslitaren** [comment]
I haven't been able to reproduce cards actually being drawn from both. However when connected, at first draw and when curse cards added and when undo/redo after a curse card added the animation will run for both decks, though no actual cards drawn (see the card counter on the decks)

this issue is fixed except for some redo situations for next version.

**Comment by Tarmslitaren** [comment]
fixed in 1.8.0 . there's a corner case when sometimes when running a redo while connected the animation will play wrong still
