### ISSUE TITLE
Question: Ways to Support

### ISSUE THREAD

**Issue by nickv2002** [Tarmslitaren/FrosthavenAssistant#136]
This tool is super valuable and I'd love to support it.

- I'm happy to donate $ for any costs (I'm guessing you can't make a profit without a license)
- I don't know Dart but work in other languages so can offer advice there when relevant
- I can help organize the issues with labels and do some basic triage
- I could use my Apple developer account to sign the Mac binaries so they don't get the Unsigned software warnings as I do for [Simple Comic](https://github.com/MaddTheSane/Simple-Comic/releases/tag/App-Store-1.9.6) (but given you already have iOS versions maybe that's a technical limitation)

Please let me know if any of these would be helpful. Thanks again!

**Comment by Tarmslitaren** [comment]
Thanks for your interest!

 - I should set up some sort of donation way, since it's a commonly requested 'feature'
 - Dart is pretty easy. If you feel like contributing with code, I can give a tour of the codebase. The most pressing issues are plainly code quality since I've pretty much only done quick and dirty solutions for a speedy development. I have a plan for that though.
 - Secondly if you are at all interested in testing, that is also needed ;)
 - For the mac issue: If you know how to sign the binaries without putting it on the store that could be helpful. The main reason I haven't added it to the app store is it would become a part of the ios release process, and I currently don't want to jeopardize the speed of that (you never know what they will complain about) but in the end I should add it there anyway.

**Comment by nickv2002** [comment]
I hear you about app review.
The way I sign & notarize Simple Comic for distribution outside the App Store is via the Xcode GUI process. It does send my binary to Apple but it's just an automated scan that takes ~15 minutes, no human review. From the Organizer window, I select the arrived build and click **Distribute** then the **Developer ID** option. But if that doesn't work for your workflow you can use other CLI tools. [Lots info & details here.](https://developer.apple.com/developer-id/)
![Xcode Sign Mac Build](https://user-images.githubusercontent.com/704392/229306709-af9c0ad9-2b5f-4bd9-b7fe-5f1cb1407938.png)

**Comment by Tarmslitaren** [comment]
added Ko-Fi donations due to high demand. You may find the link from the readme
