### ISSUE TITLE
Character tracking

### ISSUE THREAD

**Issue by Tlandon1** [Tarmslitaren/FrosthavenAssistant#15]
Would it be possible to add the ability to keep track of character attributes, items, gold, experience, etc? That would really make this app all encompassing!

**Comment by Tarmslitaren** [comment]
Experience is already supported, but besides that: I do not intend to make this app all encompassing. I believe Campaign tracking better left to campaign tracker apps, so I wouldn't need to add all kinds of special campaign rules that differ from different projects (items etc). 

 might add Character perks, but not before Frosthaven update, since I want that to be done as fast as possible, not to mention I don't want to spoil myself too much on the new classes.
