### ISSUE TITLE
Can't see what I'm editing

### ISSUE THREAD

**Issue by mentonin** [Tarmslitaren/FrosthavenAssistant#38]
When editing HP or conditions on a figure, you usually can't see the figure you are editing. This makes it harder for things like setting HP to a value

**Comment by Tarmslitaren** [comment]
I've though about that. My initial idea was to add the monster box to the status menu top so you can see the difference, I don't think it makes that much difference in the end, since all the information in the box is anyway in the menu (except the standee nr) the other idea would be to scroll the list so that the item (monster or character is always shown above the menu. Sadly it's not trivial to calculate the scroll distance in Flutter.

**Comment by Tarmslitaren** [comment]
added the monster standee wholesale yo the status menu in 1.7.0
