### ISSUE TITLE
Option to hide games/expansions

### ISSUE THREAD

**Issue by mentonin** [Tarmslitaren/FrosthavenAssistant#44]
The app could be easier to use for casual players if you could hide all content you are not using. E.g. if interested only in JotL, hide all other characters, monsters, and conditions not relevant to JotL.

For monsters, this is already somewhat implemented through a drop-down, with some caveats:
- Solo and Seeker of Xorn options show nothing
- For expansions (FC and CS) it's reasonable to expect the full set of monsters on the expansion

My idea is a global toggle of content shown (affecting monsters, characters, and conditions) and, under the "Add monster/character" menus, a drop-down filter

**Comment by Tarmslitaren** [comment]
If you want to do this you are welcome. I was going to make only a toggle for the big fan made contents Crimson Scales and Trails of Ashes (when that's added) since they are seriously bloating the amount of conditions, and are what people would most want to hide.

In addition to monsters/characters and conditions there are also  the summon items.

I think when you hide stuff it's best to let the user have more control, so having a checkbox list of all campaigns the user want to show or hide would be a good approach.

**Comment by Tarmslitaren** [comment]
fixed somewhat in 1.6.0 by toggling custom content off
