### ISSUE TITLE
Erroneous text on Blood Ooze ability card 1201

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#5]
In my physical copy of Crimson Scales, card 1201 for the Blood Ooze says:

 - Move +1
 - Attack +0
 - Target one adjacent enemy
 - Add +2 attack if the target is adjacent to at least two Blood Oozes

(I don’t know why it says “target one adjacent enemy,” since that’s the default for a melee attack.)

The card does not bear the word “range” or the range symbol, so this one is meant to be a melee attack.  But the rendering in X-Haven Assistant includes (at scenario level 2) the phrase “Range 2/3.”  Having both that and “target one adjacent enemy” confused us no end.  But looking at the physical card, it’s meant to be a melee attack, so XHA should remove the “Range 2/3.”

**Comment by Tarmslitaren** [comment]
Thanks! Will be fixed in next release.
The reason it says target one adjacent enemy on the physical card, is that Blood Ooze has an innate range stat which would make all attacks ranged unless otherwise stated. So while it is superfluous in the app where the range is added to all cards where needed (was a confusing thing in the original Gloomhaven and for no reason, since no non-ranged and ranged monster shared ability decks), it is left to make sure, for those unfamiliar with the way the app adds range .
