### ISSUE TITLE
Persistent Monster Stat Effects on Monster Ability Cards

### ISSUE THREAD

**Issue by justinkwaugh** [Tarmslitaren/FrosthavenAssistant#97]
While I know the info is on the monster stat cards, it would be nice to show the persistent effects of each monster on the ability cards too, so they don't get overlooked.  For instance if a monster has a base shield value of 1,  it would be nice to have something like  "Persistent: Shield 1" on the ability card when drawn.  Retaliate is another.  Are attack effects like the Snow Imp's brittle already being added to all attacks?

**Comment by Tarmslitaren** [comment]
All attack conditions are added, including brittle. 

Some card are already overfull of text, so would be hard to blanket add persistent shield extra, not to mention that it might. e confusing, since it is not related to the ability at all ( i e needs to ne applied before the monster's turn)

there is already a little shimmer on these persistent effects on the stat cards, so you wouldn't forget them.

 I suppose I could do more to highlight these wjn monster takes damage.

**Comment by justinkwaugh** [comment]
Fair enough, the issue is partly that I play on my phone and it's
practically impossible to see the shimmer effect and the tiny icons, but
it's easy enough to read the monster ability cards.

**Comment by Tarmslitaren** [comment]
closing as won't fix (monster stat cards are already zoomable, the original suggestion will not work well imo), however I may still do some highlighting of shield values on damage at some point
